"""create_initial_tables_users_code_reviews_findings

Revision ID: ba48c1bb8e18
Revises: 
Create Date: 2025-11-27 02:43:54.598631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba48c1bb8e18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('DEVELOPER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('daily_analysis_count', sa.Integer(), nullable=False),
    sa.Column('last_analysis_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('code_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('code_content', sa.LargeBinary(), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='reviewstatus'), nullable=False),
    sa.Column('total_findings', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_reviews_created_at'), 'code_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_code_reviews_status'), 'code_reviews', ['status'], unique=False)
    op.create_index(op.f('ix_code_reviews_user_id'), 'code_reviews', ['user_id'], unique=False)
    op.create_table('agent_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='severityenum'), nullable=False),
    sa.Column('issue_type', sa.String(length=200), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mcp_references', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['code_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_findings_agent_type'), 'agent_findings', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_findings_review_id'), 'agent_findings', ['review_id'], unique=False)
    op.create_index(op.f('ix_agent_findings_severity'), 'agent_findings', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""




    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_findings_severity'), table_name='agent_findings')
    op.drop_index(op.f('ix_agent_findings_review_id'), table_name='agent_findings')
    op.drop_index(op.f('ix_agent_findings_agent_type'), table_name='agent_findings')
    op.drop_table('agent_findings')
    op.drop_index(op.f('ix_code_reviews_user_id'), table_name='code_reviews')
    op.drop_index(op.f('ix_code_reviews_status'), table_name='code_reviews')
    op.drop_index(op.f('ix_code_reviews_created_at'), table_name='code_reviews')
    op.drop_table('code_reviews')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###